[package]
name = "chordite-chords"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
const_map.workspace = true
chordite-macros.workspace = true

