[package]
name = "chordite-rust"
version = "0.1.0"
authors = ["Mateusz Czapliński <czapkofan@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-or-later"

[[bin]]
name = "chordite-rust"
test = false
bench = false

[dependencies]
panic-halt = "0.2.0"
ufmt = "0.2.0"
nb = "1.1.0"
embedded-hal = "1.0"
avr-device = { version = "0.7", features = ["rt"] }

[dependencies.embedded-hal-v0]
# TODO: what's this and do we need it and why? copied from avr-hal/examples/atmega2560/Cargo.toml
version = "0.2.3"
package = "embedded-hal"

[dependencies.atmega-hal]
git = "https://github.com/rahix/avr-hal"
rev = "3c089795cadbbc7fa83f45958128689fee7ba1e4"
features = ["atmega32u4"]

# The latest releases of `proc-macro2` do not support the rust toolchain that
# we use.  Thus, we must fix this dependency to an older version where our
# toolchain is still supported.  See https://github.com/Rahix/avr-hal/issues/537
[build-dependencies.proc-macro2]
version = "=1.0.79"

[build-dependencies]
cc = "1.0"

# Configure the build for minimal size - AVRs have very little program memory
[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"
