[workspace]
resolver = "2"
members = ["main"]

[workspace.dependencies]
avr-device = { version = "0.7", features = ["rt"] }
chordite-chords = { path = "chords" }
chordite-macros = { path = "macros" }
const_map = { git = "https://github.com/akavel/const_map", branch = "master" }
debouncr = "0.2.2"
embedded-hal = "1.0"
nb = "1.1.0"
panic-halt = "0.2.0"
ufmt = "0.2.0"

[workspace.package]
authors = ["Mateusz Czapliński <czapkofan@gmail.com>"]
license = "AGPL-3.0-or-later"
edition = "2021"

# Configure the build for minimal size - AVRs have very little program memory
[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"


