[package]
name = "chordite-rust"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "chordite-rust"
test = false
bench = false

[dependencies]
avr-device.workspace = true
chordite-chords.workspace = true
chordite-macros.workspace = true
const_map.workspace = true
debouncr.workspace = true
embedded-hal.workspace = true
nb.workspace = true
panic-halt.workspace = true
ufmt.workspace = true

[dependencies.embedded-hal-v0]
# TODO: what's this and do we need it and why? copied from avr-hal/examples/atmega2560/Cargo.toml
version = "0.2.3"
package = "embedded-hal"

[dependencies.atmega-hal]
git = "https://github.com/rahix/avr-hal"
rev = "3c089795cadbbc7fa83f45958128689fee7ba1e4"
features = ["atmega32u4"]

# The latest releases of `proc-macro2` do not support the rust toolchain that
# we use.  Thus, we must fix this dependency to an older version where our
# toolchain is still supported.  See https://github.com/Rahix/avr-hal/issues/537
[build-dependencies.proc-macro2]
version = "=1.0.79"

[build-dependencies]
cc = "1.0"
